### ISSUE TITLE
Stood on a Prismarine truffle while breaking it and crashed.

### ISSUE THREAD

**Issue by JackRuby1** [Darkhax-Minecraft/Resource-Hogs#10] opened 2019-04-20 02:01 UTC
Crash while breaking prismarine truffle: https://pastebin.com/fAaY4dmS
Reported on SF4 trackers as well because that's where it happened https://github.com/Darkosto/SkyFactory4Issues/issues/453

**Comment by Darkhax** [comment] 2019-04-20 04:10
Thanks for reporting. This issue is caused by a race condition with Waila support, and should be fixed now.

**Closed as completed by Darkhax** 2019-04-20 04:10 UTC
